version: '3.8'
services:
  clickhouse-01:
    image: clickhouse/clickhouse-server:24.4-alpine
    user: "101:101"
    container_name: clickhouse-01
    hostname: clickhouse-01
    volumes:
      - ./fs/volumes/clickhouse-01/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./fs/volumes/clickhouse-01/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "8123:8123"
      - "9000:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-02:
    image: clickhouse/clickhouse-server:24.4-alpine
    user: "101:101"
    container_name: clickhouse-02
    hostname: clickhouse-02
    volumes:
      - ./fs/volumes/clickhouse-02/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./fs/volumes/clickhouse-02/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "8124:8123"
      - "9001:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-03:
    image: clickhouse/clickhouse-server:24.4-alpine
    user: "101:101"
    container_name: clickhouse-03
    hostname: clickhouse-03
    volumes:
      - ./fs/volumes/clickhouse-03/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./fs/volumes/clickhouse-03/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "8125:8123"
      - "9002:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-04:
    image: clickhouse/clickhouse-server:24.4-alpine
    user: "101:101"
    container_name: clickhouse-04
    hostname: clickhouse-04
    volumes:
      - ./fs/volumes/clickhouse-04/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./fs/volumes/clickhouse-04/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "8126:8123"
      - "9003:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-keeper-01:
    image: clickhouse/clickhouse-keeper:24.4-alpine
    user: "101:101"
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    volumes:
      - ./fs/volumes/clickhouse-keeper-01/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - "9181:9181"
  clickhouse-keeper-02:
    image: clickhouse/clickhouse-keeper:24.4-alpine
    user: "101:101"
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    volumes:
      - ./fs/volumes/clickhouse-keeper-02/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - "9182:9181"
  clickhouse-keeper-03:
    image: clickhouse/clickhouse-keeper:24.4-alpine
    user: "101:101"
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    volumes:
      - ./fs/volumes/clickhouse-keeper-03/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - "9183:9181"
